### ISSUE TITLE
Process Custom Fields

### ISSUE THREAD

**Issue by grefel** [grefel/press2id#10]
Process or filter custom fields. 

Use these 2 plugins:

https://www.advancedcustomfields.com/
https://de.wordpress.org/plugins/acf-to-rest-api/

**Comment by grefel** [comment]
With *acf-to-rest-api* the custom fields are exposed to **/wp-json/wp/v2/posts/acf = {}**

**Comment by haemeulrich** [comment]
I installed the mentioned plugin to write ACF to JSON. Do I have to change anything in your script to get the ACF in InDesign?

**Comment by grefel** [comment]
try the new mode Fill prepared data fields/Vorbereitete Datenfelder befüllen
