### ISSUE TITLE
Clear Overrides on Object Style after import

### ISSUE THREAD

**Issue by haemeulrich** [grefel/press2id#12]
After every import I get a style override on the object style "img". Not sure if it would be possible to reassign the style automatically after importing?
![2019-01-28_15-08-24](https://user-images.githubusercontent.com/7011448/51841329-a538fb00-230e-11e9-9b6a-73440b9d0ea5.jpg)

**Comment by grefel** [comment]
The reason for the overrid is the fixed size in the template **wordrepss_basic.idml** 
![grafik](https://user-images.githubusercontent.com/1178574/84162974-455d7300-aa71-11ea-8184-68ec624599da.png)
The image is fit to the needed size. You can change the template anytime.
