### ISSUE TITLE
Error beim Beitragimport (es kommen nur Texte keine Bilder)

### ISSUE THREAD

**Issue by corinneulrich** [grefel/press2id#14]
Hallo Gregor
Ein Teilnehmer an unserem Multichannel WordPress Seminar hat beim absaugen von einer testseite ins InDesign eine Fehlermeldung erhalten(Er kann nur Text importieren, die Bilder nicht):

Error: Error while download image [190128_jungfrau-1024x681.jpg]
from URL [https://studi4.haemeulrich-lab.com/wp-content/uploads/2019/01/190128_jungfrau-1024x681.jpg]

File was not created -> 341
Could not donwload/find image URL [https://studi4.haemeulrich-lab.com/wp-content/uploads/2019/01/190128_jungfrau-1024x681.jpg]
Error: Error while download image [190128_jungfrau_featured.jpg]
from URL [https://studi4.haemeulrich-lab.com/wp-content/uploads/2019/01/190128_jungfrau_featured.jpg]

File was not created -> 341
Could not donwload/find image URL [https://studi4.haemeulrich-lab.com/wp-content/uploads/2019/01/190128_jungfrau_featured.jpg]

Wir haben das auf Haemes InDesign auch mit dieser Seite probiert und dort hat es geklappt. An was könnte das liegen?
Lieb Grüsst Corinne Ulrich

**Comment by grefel** [comment]
Ich vermute ein Rechte Problem auf dem Rechner? Wo liegt denn die Datei? Ich habe in 2d897b478ff795eab74f0ca59e11b43a67daefbd das Logging etwas verbessert, dann sieht man auch, wo das Skript die Datei speichern wollte. Vielleicht hat InDesign dort keine Schreibrechte? 
Bei mir funktioniert es übrigens auch!
