### ISSUE TITLE
Fehler beim Platzieren

### ISSUE THREAD

**Issue by hitgoeb** [grefel/press2id#19]
«Fehler: Ungültiger Wert für Parameter "format" der Methode "exportFile". ExportFormat enumerator or String erwartet, aber INCOPY_MARKUP erhalten. Line: 396 # 30477 File: ~/Library/Preferences/Adobe%20InDesign/Version%208.0/de_DE/Scripts/Scripts%20Panel/press2id.jsx»

Weiss jemand weiter?

**Comment by grefel** [comment]
Mit welcher InDesign Version und tritt der Fehler bei allen aufruden (also auch bei Abruf z.B. von https://www.indesignblog.com/) auf?

**Comment by hitgoeb** [comment]
Danke für die Antwort. CS 6 und ja, auch bei https://www.indesignblog.com/

**Comment by grefel** [comment]
In meinem InDesign CS6 funktioniert es wunderbar. Kannst du mal die Version aus dem Branch https://github.com/grefel/press2id/tree/fix-ExportFormat.INCOPY_MARKUP testen.

**Comment by hitgoeb** [comment]
Ja, vielen Dank für die Hilfe! Hatte allerdings nicht mehr den gleichen Computer zur Verfügung. Auf einem anderen hat es so aber funktioniert!

**Comment by grefel** [comment]
Mit welchem Branch hat es unter CS6 auf dem anderen Computer funktioinert? Müsste eigentlich auch mit "master" gehen.
