### ISSUE TITLE
[Question] Images High-Res in Wordpress RGB/CYMK

### ISSUE THREAD

**Issue by miscs** [grefel/press2id#20]
Hi,

thank you for this great project!
A question concerning how to manage images which should be used in print: we can upload high-res images to wordpress but how do you manage RGB - CMYK?

Thanks!

**Comment by grefel** [comment]
When it comes to images, there are several approaches

- You could set up a RGB Workflow with a proper **Color Managment**. 
- You can **relink** the downloaded images with CMYK version on you harddrive. If they shre the same name, directly upon import. 
- Using Wordpress as an **Digital Asset Management**. I don't know the best approach on this. Maybe @haemeulrich has any ideas on this. Maybe a plugin?
