### ISSUE TITLE
JavaScript Fehler Nr. 55 + Indesign CS6  Version 8.1

### ISSUE THREAD

**Issue by SalvoGiulliano** [grefel/press2id#25]
Hello Gregor Fellenz,
fantastic script. I've watched some videos about it.

I tried the script with Indesign CS6 version 8.1. to get it running. Unfortunately with an error message.

Is it due to the outdated CS6 version?

Thank you very much and good luck for this great project.
![shoot](https://github.com/grefel/press2id/assets/169883068/a0c00090-f30b-4741-82b5-81cfd45bf1f6)

**Comment by grefel** [comment]
This is an CS6 issue. I tried to fix it in version 2.38 https://github.com/grefel/press2id/blob/master/release/press2id-latest.zip but cannot test with CS6.

**Comment by SalvoGiulliano** [comment]
Hello Gregor,
It works very well with this reaease (2.38)
Thanks you
![shoot](https://github.com/grefel/press2id/assets/169883068/ff6edf81-faeb-41a0-98fc-92cdced98e49)
