### ISSUE TITLE
Error message for installations without posts

### ISSUE THREAD

**Issue by haemeulrich** [grefel/press2id#3]
If a WordPress installation has no articles, the script simply stops without an error message. It would be cool if an error message like "you have no posts" would appear.

**Comment by grefel** [comment]
I added a localised Error Message for this case: 
![grafik](https://user-images.githubusercontent.com/1178574/51250216-fa335380-1995-11e9-92e8-c15b10e66b6c.png)

**Comment by haemeulrich** [comment]
Thank you, great!
