### ISSUE TITLE
Permalinks

### ISSUE THREAD

**Issue by haemeulrich** [grefel/press2id#4]
Have noticed that the articles will not be found if the permalinks are set to "simple" in WordPress.

**Comment by grefel** [comment]
This is a serious problem. Background is here: 
https://wordpress.stackexchange.com/questions/273144/can-i-use-rest-api-on-plain-permalink-format
We need to check the REST-API Path first ``<link rel='https://api.w.org/'`` but this will lead to some changes in the architecure of the command.

**Comment by grefel** [comment]
works now with simple permalinks as well. Currently only in branch gui-wizard
