### ISSUE TITLE
Other post types than post

### ISSUE THREAD

**Issue by pixelstrolch** [grefel/press2id#6]
A great new feature would be to fetch any installed custom post types and offer a dropdown to choose another post type than post.

**Comment by grefel** [comment]
I don't use custom post types so far. I installed the wp plugin _Custom Post Type UI_ and added a custom post type. These post types are available in the REST API. There are probably different ways to add custom post types and they might not appear in the API. 
This feature ist worth looking into it, but filtering for categories will be next :-)

**Comment by pixelstrolch** [comment]
Sounds great. Thanks a lot for the awesome work you share with us!

**Comment by berlinersueden** [comment]
Custom Post Types registered using the [register_post_type](https://developer.wordpress.org/reference/functions/register_post_type/) function can be fetched at the moment by replacing `posts` in press2id.jsx on lines [163](https://github.com/grefel/press2id/blob/master/Scripts%20Panel/press2id.jsx#L163), [695](https://github.com/grefel/press2id/blob/master/Scripts%20Panel/press2id.jsx#L695) and [699](https://github.com/grefel/press2id/blob/master/Scripts%20Panel/press2id.jsx#L699) before running the import.

**Comment by grefel** [comment]
works via dropdown in branch gui-wizard
